[dev]
  autoLaunch = false

[build]
  command = ""
  publish = "netlify/edge-functions"

[[edge_functions]]
  path = "/game/new"
  function = "game-new"

[[edge_functions]]
  path = "/game/*/try/*"
  function = "game-attempt"

[[edge_functions]]
  path = "/game/*"
  function = "game-id"
