[dev]
  framework = "#static"

[build]
  command = ""
  publish = "netlify/edge-functions"

[functions]
  deno_import_map = "./config/import_map.json"

[[edge_functions]]
  path = "/game/new"
  function = "game-new"

[[edge_functions]]
  path = "/game/*/try/*"
  function = "game-attempt"

[[edge_functions]]
  path = "/game/*"
  function = "game-id"
