name: Lint, Test, & Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch triggering commit
        uses: actions/checkout@v4
      - run: |
          npm ci
          npm run lint
          npm run test
          npm run build
